project:
  type: website
  output-dir: docs
metadata:
  date-modified: last-modified
website:
  page-navigation: true
  title: "Jishen Du"
  site-url: https://lianyujun.github.io
  favicon: images/site-logo.png
  repo-url: https://github.com/lianyujun/lianyujun.github.io
  repo-actions: []
  

  page-footer:
    left: |
      Last updated: {{< meta date-modified >}}
    right: |
      Any suggestion about what should be put here?
    
  navbar: 
    background: "#A9CCE3"
    search: false
    right: 
      - text: "Home"
        href: index.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Teaching"
        href: teaching.qmd
      #- text: "Blogss"
      #  href: blog.qmd
      #- text: "Codes"
      #  href: codes.qmd
      - text: "中文"
        href: Chinese.qmd
      - text: "CV"
        href: CV.pdf
        target: _blank

format:
  html:
    theme: styles.scss
    toc: true            # 启用目录
    toc-position: right  # 将目录放置在页面的右侧
    toc-depth: 3         # 设置目录的深度，数字越大，目录越详细
    